"""Training-only adapters around the unchanged QuerySplat inference graph."""

from .vggt_input_pass import VGGTInputPassOutput, forward_vggt_input_once
from .self_calibration import (
    CameraAlignmentMetrics,
    CameraOnlyOutput,
    SelfCalibratedVGMOutput,
    Sim3Transform,
    apply_sim3_to_cameras,
    camera_alignment_metrics,
    cam_view_to_c2w,
    c2w_to_cam_view,
    estimate_sim3_from_cameras,
    forward_self_calibrated_vgm,
    forward_vggt_camera_only,
)
from .dual_branch_forward import (
    DualBranchForwardOutput,
    build_dual_branch_latent,
    decode_and_render_from_self_calibration,
    forward_querysplat_training,
)
from .losses import (
    LinearWeightSchedule,
    QuerySplatLossConfig,
    build_lpips_vgg,
    compute_bidirectional_chamfer_loss,
    compute_opacity_floor_loss,
    compute_photometric_losses,
    compute_querysplat_losses,
    compute_visibility_loss,
    sample_vggt_depth_pointcloud,
)
from .state import (
    ExponentialMovingAverage,
    OptimizerConfig,
    build_adamw,
    build_warmup_cosine_scheduler,
    load_training_checkpoint,
    save_training_checkpoint,
)
from .fixed_scene_cache import (
    FixedSceneVGMCache,
    materialize_fixed_scene_self_calibration,
    prepare_fixed_scene_vgm_cache,
)
from .multiscene import (
    DL3DVLoaderBundle,
    QuerySplatTrainingModule,
    build_dl3dv_dataloader,
    prepare_querysplat_images,
    set_dl3dv_epoch,
)

__all__ = [
    "CameraAlignmentMetrics",
    "CameraOnlyOutput",
    "DualBranchForwardOutput",
    "DL3DVLoaderBundle",
    "ExponentialMovingAverage",
    "FixedSceneVGMCache",
    "LinearWeightSchedule",
    "OptimizerConfig",
    "QuerySplatLossConfig",
    "QuerySplatTrainingModule",
    "SelfCalibratedVGMOutput",
    "Sim3Transform",
    "VGGTInputPassOutput",
    "apply_sim3_to_cameras",
    "build_dual_branch_latent",
    "build_adamw",
    "build_lpips_vgg",
    "build_dl3dv_dataloader",
    "build_warmup_cosine_scheduler",
    "camera_alignment_metrics",
    "cam_view_to_c2w",
    "c2w_to_cam_view",
    "decode_and_render_from_self_calibration",
    "compute_bidirectional_chamfer_loss",
    "compute_opacity_floor_loss",
    "compute_photometric_losses",
    "compute_querysplat_losses",
    "compute_visibility_loss",
    "estimate_sim3_from_cameras",
    "forward_self_calibrated_vgm",
    "forward_querysplat_training",
    "forward_vggt_camera_only",
    "forward_vggt_input_once",
    "load_training_checkpoint",
    "materialize_fixed_scene_self_calibration",
    "prepare_fixed_scene_vgm_cache",
    "prepare_querysplat_images",
    "sample_vggt_depth_pointcloud",
    "save_training_checkpoint",
    "set_dl3dv_epoch",
]
